version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "Admin123"
      MYSQL_DATABASE: "asset_notif"
    volumes: 
      - ./testdb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  app: 
    build: .
    environment:
      TG_KEY: "5"
      TG_IDS: "7"
      CF_KEY: "Q"
      ARVAN_KEY: "A"
      DB_DRIVER: "mysql"
      DS_NAME: "root:Admin123@tcp(db:3306)/asset_notif"
      MYSQL_HOST: "db"
      MYSQL_PASSWORD: "Admin123"
      MYSQL_DB: "asset_notif"
      MYSQL_USER: "root"
      MYSQL_PORT: "3306"
    depends_on:
      - db
    ports:
      - "9000:9000"
